[phases.setup]
nixPkgs = ['...', 'nodejs', 'python']

[phases.build]
cmd = ["cargo build --release", "npm --prefix frontend install", "npm --prefix frontend run build"]

[start]
cmd = 'bin/kalkafox-img'