[phases.setup]
nixPkgs = ['...', 'nodejs', 'python']

[phases.build]
cmd = ["npm --prefix frontend install", "npm --prefix frontend run build", "cargo build --release"]

[start]
cmd = 'bin/kalkafox-img'