[phases.setup]
nixPkgs = ['...', 'nodejs', 'python']

[phases.build]
cmds = ['npm install --prefix frontend", "cd frontend && npx vite build --prefix frontend && cd ..', 'cargo build --release']

[start]
cmd = 'target/release/kalkafox-img'